# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-06 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateTimeField(default='1981-08-31'),
        ),
    ]
